import re

reg = re.compile("(Dr\. |Prof\. )*([A-Z][a-z]+) ([a-zA-Z\.]*)( )?([A-Z][a-z]+)(, PhD|, MSc|, KG|, KT|, PC|, ADC|, Duke of [A-Za-z]*)*")

m = reg.match("Uwe Meier")
print(m.group(0))
m = reg.match("Prof. Dr. Chris C Schmidt")
print(m.group(0))
m = reg.match("Hanna J Gruber, PhD")
print(m.group(0))
m = reg.match("Hanna J. Gruber, PhD")
print(m.group(0))
m = reg.match("Hanna Jana Gruber, PhD, MSc")
print(m.group(0))
m = reg.match("Dr. Uwe Meier, MSc")
print(m.group(0))
m = reg.match("Dr. Alfred Nobel, PhD, PhD, PhD, MSc")
print(m.group(0))
m = reg.match("Dr. Dr. Dr. Theodore Hesburgh, PhD, PhD, PhD, MSc")
print(m.group(0))
m = reg.match("Albert KD Klein, PhD, PhD, PhD, MSc")
print(m.group(0))
m = reg.match("Prince William, Duke of Manchester, KG, KT, PC, ADC")
print(m.group(0))
